#!/usr/bin/ruby
source 'https://rubygems.org'
gem 'pry'
gem 'pry-rescue'

gem 'minitest'
gem 'minitest-reporters'

gem "hsss"

gem "binding_of_caller"
gem "rspec"
gem "async"
gem "async-io"
gem "async-await"
gem "async-rspec"

